### PR TITLE
CID decode bug fix

### PR DESCRIPTION
**Pull request by brycewilkins**
CID decode bug fix.

Correct field decoding according to JEDEC standard:
image

### CODE REVIEW

**Review by mparanjpe — APPROVED** [review]
👍

**Comment by larson-whisper** [comment]
LGTM.  Should we push this upstream as well?

**Comment by brycewilkins** [comment]
> LGTM. Should we push this upstream as well?

Yeah, I can do that separately as a good open-source contributor :) 

Though in the near future I think we might be able to drop `mcux-sdk-middleware-sdmmc` completely. In Zephyr 3.1.0 a generic SDMMC disk driver has been added within Zephyr itself. I think it will be beneficial to switch to it for future support.

**Comment by brycewilkins** [comment]
> LGTM. Should we push this upstream as well?

Submitted upstream: https://github.com/NXPmicro/mcux-sdk-middleware-sdmmc/pull/1

**Pull request merged**
